version: '2'
services:
  project:
    build: .
    links:
      - redis
    command: "bash -c '/usr/local/bin/composer install && vendor/phpunit/phpunit/phpunit'"
    environment:
          - REDIS_HOST=redis
    volumes:
      - .:/var/app
  redis:
    image: redis
    logging:
          driver: "none"
    ports:
      - 6379:6379
